=== haojieliu/osiris/osiris/OsirisXML/LadderSpecifications/ILSAndLadderInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2018 rel. 2 (http://www.altova.com) by Robert Goor (NCBI/NLM/NIH) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="LaneStandardData">
		<xs:sequence minOccurs="0">
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="DisplayName" type="xs:string" minOccurs="0"/>
			<xs:element name="Characteristics" type="xs:string"/>
			<xs:element name="RelativeHeights" type="xs:string" minOccurs="0"/>
			<xs:element name="Omissions" type="xs:string" minOccurs="0"/>
			<xs:element name="CorrelationAcceptanceThreshold">
				<xs:annotation>
					<xs:documentation>Minimum correlation of spacing (after quadratic transform) to avoid failing lane standard</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:minExclusive value="0.0"/>
						<xs:maxExclusive value="1.0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CorrelationAutoAcceptanceThreshold">
				<xs:annotation>
					<xs:documentation>Minimum correlation of spacing (after quadratic transform) to avoid "requires human review" message for lane standard</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:minExclusive value="0.0"/>
						<xs:maxExclusive value="1.0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="AltSpacing" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="KitData">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Version" type="xs:string" default="2.0"/>
				<xs:element name="LaneStandards">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ILS" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ILSName" type="xs:string"/>
										<xs:element name="DyeName" type="xs:string"/>
										<xs:choice>
											<xs:element name="LaneStandard" type="LaneStandardData" maxOccurs="unbounded">
												<xs:annotation>
													<xs:documentation>For kit with single list of ILS</xs:documentation>
												</xs:annotation>
											</xs:element>
											<xs:element name="SubFamily" maxOccurs="unbounded">
												<xs:annotation>
													<xs:documentation>ILS Family, new in v2.7</xs:documentation>
												</xs:annotation>
												<xs:complexType>
													<xs:sequence>
														<xs:element name="SubFamilyName" type="xs:string"/>
														<xs:element name="LaneStandard" type="LaneStandardData" maxOccurs="unbounded"/>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
										</xs:choice>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="Kits"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Kits">
		<xs:annotation>
			<xs:documentation>List of Marker Sets with channels, alleles, etc</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="Set">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="KitName" type="xs:string"/>
							<xs:element name="FileName" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== haojieliu/osiris/osiris/OsirisXML/LadderSpecifications/ILSAndLadderInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<KitData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ILSAndLadderInfo.xsd">
  <Version>2.7</Version>
  <LaneStandards>
    <ILS>
      <ILSName>ABI-ROX-500</ILSName>
      <DyeName>ROX</DyeName>
      <LaneStandard>
        <Name>ABI-ROX500</Name>
        <DisplayName>75-500</DisplayName>
        <Characteristics>75 100 139 150 160 200 250 300 340 350 400 450 490 500</Characteristics>
        <RelativeHeights>MH MH MH MH MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
        <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>       
        <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
      </LaneStandard>
      <LaneStandard>
        <Name>ABI-ROX450</Name>
        <DisplayName>75-450</DisplayName>
        <Characteristics>75 100 139 150 160 200 250 300 340 350 400 450</Characteristics>
        <RelativeHeights>MH MH MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
        <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
        <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
      </LaneStandard>
      <LaneStandard>
        <Name>ABI-ROX400</Name>
        <DisplayName>75-400</DisplayName>
        <Characteristics>75 100 139 150 160 200 250 300 340 350 400</Characteristics>
        <RelativeHeights>MH MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
        <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
        <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
      </LaneStandard>
      <LaneStandard>
        <Name>ABI-ROX350</Name>
        <DisplayName>75-350</DisplayName>
        <Characteristics>75 100 139 150 160 200 250 300 340 350</Characteristics>
        <RelativeHeights>MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
        <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
        <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
      </LaneStandard>
      <LaneStandard>
        <Name>ABI-ROX100-500</Name>
        <DisplayName>100-500</DisplayName>
        <Characteristics>100 139 150 160 200 250 300 340 350 400 450 490 500</Characteristics>
        <RelativeHeights>MH MH MH MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
        <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
        <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
      </LaneStandard>
      <LaneStandard>
        <Name>ABI-ROX100-400</Name>
        <DisplayName>100-400</DisplayName>
        <Characteristics>100 139 150 160 200 250 300 340 350 400</Characteristics>
        <RelativeHeights>MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
        <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
        <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
      </LaneStandard>
    </ILS>
    <ILS>
      <ILSName>ABI-LIZ-500</ILSName>
      <DyeName>LIZ</DyeName>
      <SubFamily>
        <SubFamilyName>ABI-LIZ-500-MID-INTACT</SubFamilyName>
        <LaneStandard>
          <Name>ABI-LIZ500</Name>
          <DisplayName>75-500</DisplayName>
          <Characteristics>75 100 139 150 160 200 250 300 340 350 400 450 490 500</Characteristics>
          <RelativeHeights>MH MH MH MH MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
          <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
          <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
        </LaneStandard>
        <LaneStandard>
          <Name>ABI-LIZ450</Name>
          <DisplayName>75-450</DisplayName>
          <Characteristics>75 100 139 150 160 200 250 300 340 350 400 450</Characteristics>
          <RelativeHeights>MH MH MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
          <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
          <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
        </LaneStandard>
        <LaneStandard>
          <Name>ABI-LIZ400</Name>
          <DisplayName>75-400</DisplayName>
          <Characteristics>75 100 139 150 160 200 250 300 340 350 400</Characteristics>
          <RelativeHeights>MH MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
          <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
          <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
        </LaneStandard>
        <LaneStandard>
          <Name>ABI-LIZ350</Name>
          <DisplayName>75-350</DisplayName>
          <Characteristics>75 100 139 150 160 200 250 300 340 350</Characteristics>
          <RelativeHeights>MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
          <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
          <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
        </LaneStandard>
      </SubFamily>
      <SubFamily>
        <SubFamilyName>ABI-LIZ-500-MID-OMIT</SubFamilyName>
        <LaneStandard>
          <Name>ABI-LIZ-LESS250-500</Name>
          <DisplayName>75-500 OMIT 250</DisplayName>
          <Characteristics>75 100 139 150 160 200 300 340 350 400 450 490 500</Characteristics>
          <RelativeHeights>MH MH MH MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
          <Omissions>250</Omissions>
          <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
          <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
        </LaneStandard>
        <LaneStandard>
          <Name>ABI-LIZ-LESS250-450</Name>
          <DisplayName>75-450 OMIT 250</DisplayName>
          <Characteristics>75 100 139 150 160 200 300 340 350 400 450</Characteristics>
          <RelativeHeights>MH MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
          <Omissions>250</Omissions>
          <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
          <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
        </LaneStandard>
        <LaneStandard>
          <Name>ABI-LIZ-LESS250-400</Name>
          <DisplayName>75-400 OMIT 250</DisplayName>
          <Characteristics>75 100 139 150 160 200 300 340 350 400</Characteristics>
          <RelativeHeights>MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
          <Omissions>250</Omissions>
          <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
          <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
        </LaneStandard>
        <LaneStandard>
          <Name>ABI-LIZ-LESS250-350</Name>
          <DisplayName>75-350 OMIT 250</DisplayName>
          <Characteristics>75 100 139 150 160 200 300 340 350</Characteristics>
          <RelativeHeights>MH MH MH MH MH MH MH MH MH</RelativeHeights>
          <Omissions>250</Omissions>
          <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
          <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
        </LaneStandard>
        <LaneStandard>
          <Name>ABI-LIZ-LESS340-500</Name>
          <DisplayName>75-500 OMIT 340</DisplayName>
          <Characteristics>75 100 139 150 160 200 250 300 350 400 450 490 500</Characteristics>
          <RelativeHeights>MH MH MH MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
          <Omissions>340</Omissions>
          <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
          <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
        </LaneStandard>
        <LaneStandard>
          <Name>ABI-LIZ-LESS340-450</Name>
          <DisplayName>75-450 OMIT 340</DisplayName>
          <Characteristics>75 100 139 150 160 200 250 300 350 400 450</Characteristics>
          <RelativeHeights>MH MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
          <Omissions>340</Omissions>
          <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
          <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
        </LaneStandard>
        <LaneStandard>
          <Name>ABI-LIZ-LESS340-400</Name>
          <DisplayName>75-400 OMIT 340</DisplayName>
          <Characteristics>75 100 139 150 160 200 250 300 350 400</Characteristics>
          <RelativeHeights>MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
          <Omissions>340</Omissions>
          <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
          <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
        </LaneStandard>
        <LaneStandard>
          <Name>ABI-LIZ-LESS250and340-500</Name>
          <DisplayName>75-500 OMIT 250, 340</DisplayName>
          <Characteristics>75 100 139 150 160 200 300 350 400 450 490 500</Characteristics>
          <RelativeHeights>MH MH MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
          <Omissions>250 340</Omissions>
          <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
          <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
        </LaneStandard>
        <LaneStandard>
          <Name>ABI-LIZ-LESS250and340-450</Name>
          <DisplayName>75-450 OMIT 250, 340</DisplayName>
          <Characteristics>75 100 139 150 160 200 300 350 400 450</Characteristics>
          <RelativeHeights>MH MH MH MH MH MH MH MH MH MH</RelativeHeights>
          <Omissions>250 340</Omissions>
          <CorrelationAcceptanceThreshold>0.993</CorrelationAcceptanceThreshold>
          <CorrelationAutoAcceptanceThreshold>0.9975</CorrelationAutoAcceptanceThreshold>
        </LaneStandard>
        <LaneStandard>
          <Name>ABI-LIZ-LESS250and340-400</Name>
          <DisplayName>75-400 OMIT 250, 340</DisplayName>
