=== haojieliu/osiris/osiris/OsirisXML/LadderSpecifications/kitcolors2.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2018 rel. 2 (http://www.altova.com) by rmgoor (NCBI/NLM/NIH) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="Dyes">
		<xs:annotation>
			<xs:documentation>Collection of dyes and colors</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="Dye"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Dye">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Color"/>
				<xs:element ref="Names"/>
				<xs:element ref="analyzed">
					<xs:annotation>
						<xs:documentation>RGB(...,...,...)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="raw">
					<xs:annotation>
						<xs:documentation>RGB(...,...,...)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="ladder">
					<xs:annotation>
						<xs:documentation>RGB(...,...,...)</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Color"/>
	<xs:element name="Names">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="Name"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Name"/>
	<xs:element name="analyzed"/>
	<xs:element name="raw"/>
	<xs:element name="ladder"/>
</xs:schema>

=== haojieliu/osiris/osiris/OsirisXML/LadderSpecifications/kitcolors2.0.xml
<?xml version="1.0" standalone="yes"?>
<Dyes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="kitcolors2.0.xsd">
  <Dye>
	  <Color>BLUE</Color>
	  <Names>
		<Name>5-FAM</Name>
		<Name>FL</Name>
		<Name>FAM</Name>
		<Name>FL-6C</Name>
		<Name>Blue</Name>
		<Name>BLUE</Name>
	  </Names>
      <analyzed>RGB(0,0,144)</analyzed>
      <raw>RGB(113,113,153)</raw>
      <ladder>RGB(144,144,191)</ladder>
   </Dye>
   <Dye>
	  <Color>GREEN</Color>
	  <Names>
		  <Name>JOE</Name>
		  <Name>VIC</Name>
		  <Name>JOE-6C</Name>
		  <Name>5-HEX</Name>
		  <Name>Green</Name>
		  <Name>GREEN</Name>
	  </Names>
      <analyzed>RGB(0,144,0)</analyzed>
      <raw>RGB(118,150,118)</raw>
      <ladder>RGB(116,191,116)</ladder>
   </Dye>
    <Dye>
	  <Color>YELLOW</Color>
	  <Names>
		  <Name>NED</Name>
		  <Name>TMR</Name>
		  <Name>TMR-ET</Name>
		  <Name>TAMRA</Name>
		  <Name>TMR-6C</Name>
		  <Name>L552</Name>
		  <Name>Yellow</Name>
		  <Name>YELLOW</Name>
	  </Names>
       <analyzed>RGB(125,125,35)</analyzed>
      <raw>RGB(131,131,100)</raw>
      <ladder>RGB(165,165,97)</ladder>
   </Dye>
   <Dye>
	  <Color>RED</Color>
	  <Names>
		  <Name>ROX</Name>
		  <Name>PET</Name>
		  <Name>CXR</Name>
		  <Name>CXR-ET</Name>
		  <Name>CXR-6C</Name>
		  <Name>TAZ</Name>
		  <Name>LR600</Name>
		  <Name>Red</Name>
		  <Name>RED</Name>
	  </Names>
      <analyzed>RGB(144,0,0)</analyzed>
      <raw>RGB(144,96,96)</raw>
      <ladder>RGB(191,120,120)</ladder>
   </Dye>
   <Dye>
	  <Color>ORANGE</Color>
	  <Names>
		  <Name>LIZ</Name>
		  <Name>CC5</Name>
		  <Name>GRODY</Name>
		  <Name>WEN-6C</Name>
		  <Name>WEN</Name>
		  <Name>BTO</Name>
		  <Name>DY632</Name>
		  <Name>AF-633</Name>
		  <Name>Orange</Name>
		  <Name>ORANGE</Name>
	  </Names>
      <analyzed>RGB(180,90,0)</analyzed>
      <raw>RGB(144,96,48)</raw>
      <ladder>RGB(191,144,98)</ladder>
   </Dye>
   <Dye>
	  <Color>PURPLE</Color>
	  <Names>
		  <Name>SID</Name>
		  <Name>TOM-6C</Name>
		  <Name>TOM</Name>
		  <Name>TET-592</Name>
		  <Name>Purple</Name>
		  <Name>PURPLE</Name>
	  </Names>
      <analyzed>RGB(144,0,144)</analyzed>
      <raw>RGB(144,96,144)</raw>
      <ladder>RGB(144,120,144)</ladder>
   </Dye>
</Dyes>
